### ISSUE TITLE
JHU_COVID_19 still has hiccups in the Mar-23 range when the data format was changed.

### ISSUE THREAD

**Issue by adder5dv** [starschema/COVID-19-data#103]
```
Country/Region | Province/State | County | FIPS | Date | Case_Type | Cases | Long | Lat | ISO3166-1 | ISO3166-2 | Difference | Last_Update_Date
France | French Polynesia |   |   | 3/22/2020 | Confirmed | 15 | 149.4068 | -17.6797 | FR | PF | 0 | 01:55.2
France | French Polynesia |   |   | 3/23/2020 | Confirmed | 19874 | -149.407 | -17.6797 | FR | PF | 19859 | 01:55.2
France | French Polynesia |   |   | 3/24/2020 | Confirmed | 25 | -149.407 | -17.6797 | FR | PF | -19849 | 01:55.2
```
Cases is clearly not monotonic, and jumpes by 19849 cases in one day, then disappears.

**Comment by chrisvoncsefalvay** [comment]
Hi @adder5dv – thanks for pointing this out. I'm afraid that this is an issue with the JHU data:

<img width="697" alt="Screenshot 2020-03-26 at 23 02 00" src="https://user-images.githubusercontent.com/2670100/77717067-e8940580-6fb5-11ea-9ee4-7415473e3493.png">

It appears that the data for France was replicated into French Polynesia. This is a [known issue](https://github.com/CSSEGISandData/COVID-19/issues/1515) and it was hitherto only fixed prospectively. If there will not be a retrospective fix for French Polynesia, we may do a manual fix.

Thanks again for bringing this to our attention!
