### ISSUE TITLE
JHU_COVID-19 data for 1/22 (initial day) has lots of negative values for Difference

### ISSUE THREAD

**Issue by adder5dv** [starschema/COVID-19-data#104]
**Describe the bug**
Lots of US States have negative initial values for "Difference" column on 1/22. Other data seems to have random negative values for Difference. How should I treat these negative values in the data?

**To Reproduce**
look at 1/22 data in JHU_COVID-19

**Expected behavior**
No negative values for Difference (Confirmed should be monotonic)

**Comment by chrisvoncsefalvay** [comment]
Thanks, we're on it! :)

`Confirmed` will not necessarily be monotonic:

* Some data points are not initially assigned a county. These go to a county called `Unassigned, <State>`, e.g. `Unassigned, WA`. Once they're allocated to a county, the `Unassigned`  county will experience a negative in confirmed cases. You can control for this by simply dropping `Unassigned` cases, which will make your county level data a little 'laggy' (a day or two maybe), but vastly reduce US negatives.
* Some source data is experiencing negative confirmed deltas. [In some cases, this is a bug](https://github.com/CSSEGISandData/COVID-19/issues/1661), in others, it may be an issue with the way the data is delivered.

We're working hard on improving data quality and reducing these issues. Your comments play a crucial role in ironing out these things. Thank you.

**Comment by adder5dv** [comment]
Thanks, it's great to understand that source of differences! I'll try to account for it going forward. Mostly, I need to move away from using confirmed as a non-aggregated source to pivot freely on. Ultimately you need to use the cumulative value on a given day only, unless you are reporting relative changes. Then, when reporting relative changes, you have to be careful of how those values shift in assignment. I'd also noticed from the source data, that even what I would think are individual grains even have multiple rows (ie, a given country, state, county, day could still have several entries). Makes it tricky to present accurate numbers and still let users pivot.
