### ISSUE TITLE
Lat Long is reversed in the Healthsites data

### ISSUE THREAD

**Issue by stitchapalacio** [starschema/COVID-19-data#108]
**Description**
The lat and long columns appear to be mislabeled. 

**Screenshots**
Here is what is shown in the data:
![image](https://user-images.githubusercontent.com/51167300/77791949-dfe71200-703d-11ea-8b7b-2381f8073759.png)

here is what is shown on the Healthsites map:
![image](https://user-images.githubusercontent.com/51167300/77791679-7c5ce480-703d-11ea-8620-b629ea9140d9.png)

**Additional context**

**Comment by chrisvoncsefalvay** [comment]
Hi @stitchapalacio, thanks for spotting this. There is now a [PR in to fix this](https://github.com/starschema/COVID-19-data/pull/110).
