### ISSUE TITLE
Fix NYT_US_COVID19's FIPS coding

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [starschema/COVID-19-data#137]
**Is your feature request related to a problem? Please describe.**
NYT data has FIPS as a numeric format (`NUMBER(38,0)`) in Snowflake. This makes it difficult to join to other FIPS codes, where FIPS codes are provided as `VARCHAR`s (`VARCHAR(5)` or the more expensive `VARCHAR(16777216)` aka `text`). 

**Describe the solution you'd like**
* Set `NYT_US_COVID19`.`FIPS` type to `VARCHAR(5)`.
* Change `METADATA` accordingly.

<img width="283" alt="Screenshot 2020-03-31 at 11 37 44" src="https://user-images.githubusercontent.com/2670100/78045523-0bbb0e00-7344-11ea-9c76-6c74cbecf6df.png">

**Comment by tfoldi** [comment]
seems the CSV already truncated to integers, the notebook has to be fixed too

**Comment by tfoldi** [comment]
Fixed in snowflake prod too
