### ISSUE TITLE
Access Denied S3

### ISSUE THREAD

**Issue by cyzanfar** [starschema/COVID-19-data#154]
**Describe the bug**
Getting `Acces denied` when reading file from s3 using pandas

**To Reproduce**
```
df = pd.read_csv('s3://starschema.covid/CT_US_COVID_TESTS.csv')
```

**Comment by chrisvoncsefalvay** [comment]
Hy @cyzanfar – this is an S3 link, which Pandas cannot generally resolve on its own. If you right-click and copy the link, you get the HTTPS link, which Pandas will be able to read (for this file, it's https://s3-us-west-1.amazonaws.com/starschema.covid/CT_US_COVID_TESTS.csv ). 

I hope that helps. :)

**Comment by cyzanfar** [comment]
Hey! Thanks, I figured it out 👍
