### ISSUE TITLE
Request to include business metadata directly in the table and column comment fields

### ISSUE THREAD

**Issue by sfc-gh-space** [starschema/COVID-19-data#158]
**Is your feature request related to a problem? Please describe.**
Snowflake has the capability to include metadata within schema, table, and column comments. Besides Snowflake native commands, some third-party modeling, data governance and metadata solutions can read these fields as they ingest the table schemas. Examples of Snowflake commands that use these fields:

```
show schemas like 'public';
show tables;
desc table WHO_SITUATION_REPORTS;
```

**Describe the solution you'd like**
I would like the table owner to issue these commands to add the comment fields. This is a one time non-invasive process. I will supply commands like below to run. If you agree, I will submit for the rest of the tables. I will get the comment values from the METADATA table.

```
alter schema PUBLIC SET COMMENT = 'COVID-19 Data from Starschema Limited';

alter table CT_US_COVID_TESTS alter (
        COUNTRY_REGION COMMENT 'ISO-3166-1 entity name (United States)',
	PROVINCE_STATE COMMENT 'ISO-3166-2 entity name (U.S. State)',
	DATE COMMENT 'Date of data point',
	POSITIVE COMMENT 'Positive cases on date of report',
	POSITIVE_SINCE_PREVIOUS_DAY COMMENT 'Positive cases since previous date of report',
	NEGATIVE COMMENT 'Negative tests on date of report',
	NEGATIVE_SINCE_PREVIOUS_DAY COMMENT 'Negative tests since previous date of report',
	PENDING COMMENT 'Pending tests on date of report',
	PENDING_SINCE_PREVIOUS_DAY COMMENT 'Pending tests since previous date of report',
	DEATH COMMENT 'Deaths attributed to COVID-19 on date of report',
	DEATH_SINCE_PREVIOUS_DAY COMMENT 'Deaths attributed to COVID-19 since previous date of report',
	HOSPITALIZED COMMENT 'Hospitalized cases of COVID-19 on date of report',
	HOSPITALIZED_SINCE_PREVIOUS_DAY COMMENT 'Hospitalized cases of COVID-19 since previous date of report',
	TOTAL COMMENT 'Total of positive, negative, pending and deaths on date of report',
	TOTAL_SINCE_PREVIOUS_DAY COMMENT 'Total of positive, negative, pending and deaths on date of report attributed to COVID-19 since previous date of report',
	ISO3166_1 COMMENT 'ISO-3166-1 code for geography of report (Country)',
	ISO3166_2 COMMENT 'ISO-3166-2 code for geography of report (States)',
	LAST_UPDATED_DATE COMMENT 'Timestamp of last update (UTC)'
);

alter table CT_US_COVID_TESTS SET COMMENT='JHU US COVID-19 testing and mortality';
```

**End Result**
`DESC table CT_US_COVID_TESTS;`

![image](https://user-images.githubusercontent.com/53441007/78311448-7cb21f80-7516-11ea-8cea-f72ac4b48d26.png)

**Comment by tfoldi** [comment]
I change the metadata notebook to create a SQL file to comment all objects with descriptions. This is the URL of the generated file: https://s3-us-west-1.amazonaws.com/starschema.covid/METADATA_COMMENT_DB_OBJECTS.sql 

I need to write a small script/dag to execute it everything the metadata changes - currently, it is manual

**Comment by tfoldi** [comment]
@chrisvoncsefalvay This is the list of columns without documentation:


```
select TABLE_NAME, COLUMN_NAME, COMMENT
from INFORMATION_SCHEMA.COLUMNS
where TABLE_CATALOG = 'COVID19'
  and TABLE_SCHEMA = 'PUBLIC'
  and COMMENT is null
order by 1, 2;```
