### ISSUE TITLE
Add new data source: Belgium data from Sciensano

### ISSUE THREAD

**Issue by danteo13** [starschema/COVID-19-data#162]
**Data source description**
Sciensano, the Belgian institute for health, is responsible for the epidemiological follow-up of the COVID-19 epidemic in collaboration with its partners and other healthcare actors. The data collected can provide insight into the dynamics of the epidemic, help to anticipate different scenarios and to elaborate possible measures to curb the spread of the virus.
From 31 March, Sciensano will make a set of data available to interested parties on a daily basis. This information is a support for decision making in the control of the epidemic. To achieve its mission, Sciensano has reinforced or set up different surveillance systems thanks to the participation of health professionals.

**Data source location**
https://epistat.wiv-isp.be/covid/

**Data format**
csv and xlsx

**Data issues**
Not really a DQ issue, but daily numbers from previous days are not 'fixed' and can be adjusted upwards later.
In the municipality files, rows with lower than 5 cases gets stored as a string: '<5'.

**Data Validation**
The daily numbers do not match the JHU numbers. Upon further inspection however, the total of each daily file for Age/Sex do match the JHU numbers from a different perspective. For example, the file from April 2 only contains data until March 31st (plus a tiny portion of April 1st), but the total of the file matches what John Hopkins reports on April 2nd. Plus, as mentioned previously, numbers can get adjusted upwards later. These adjustments are not reflected in the JHU numbers.

**Comment by chrisvoncsefalvay** [comment]
Thanks Daniel, let us take a look at this.

My approach will be to code `<5` as 4 – we'll possibly overestimate cases, but unfortunately we'll _have_ to assign some numeric value to this.

**Comment by chrisvoncsefalvay** [comment]
DDL:

```sql
CREATE OR REPLACE TABLE SCS_BE_DETAILED_PROVINCE_CASE_COUNTS (
    PROVINCE VARCHAR(128),
    REGION VARCHAR(128),
    SEX VARCHAR(1) NOT NULL,
    AGEGROUP VARCHAR(16) NOT NULL,
    DATE DATE,
    ISO3166_1 VARCHAR(2) NOT NULL,
    ISO3166_2 VARCHAR(3),
    ISO3166_3 VARCHAR(3),
    NEW_CASES NUMERIC(38,0),
    TOTAL_CASES NUMERIC(38,0),
    LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL
);

CREATE OR REPLACE TABLE SCS_BE_DETAILED_HOSPITALISATIONS (
    PROVINCE VARCHAR(128),
    REGION VARCHAR(128) NOT NULL,
    DATE DATE NOT NULL,
    NR_REPORTING NUMERIC(38,0),
    TOTAL_IN NUMERIC(38,0),
    TOTAL_IN_ICU NUMERIC(38,0),
    TOTAL_IN_RESP NUMERIC(38,0),
    TOTAL_IN_ECMO NUMERIC(38,0),
    NEW_IN NUMERIC(38,0),
    NEW_OUT NUMERIC(38,0),
    ISO3166_1 VARCHAR(2) NOT NULL,
    ISO3166_2 VARCHAR(3),
    ISO3166_3 VARCHAR(3),
    LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL
);

CREATE OR REPLACE TABLE SCS_BE_DETAILED_MORTALITY (
    REGION VARCHAR(128) NOT NULL,
    SEX VARCHAR(1) NOT NULL,
    AGEGROUP VARCHAR(16) NOT NULL,
    DATE DATE NOT NULL,
    DEATHS NUMERIC(38,0),
    ISO3166_1 VARCHAR(2) NOT NULL,
    ISO3166_2 VARCHAR(3),
    LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL
);

CREATE OR REPLACE TABLE SCS_BE_DETAILED_TESTS (
    DATE DATE NOT NULL,
    TESTS NUMERIC(38,0),
    LAST_UPDATED_DATE TIMESTAMP_NTZ(9) NOT NULL
);
```
