### ISSUE TITLE
Please add TABLE and COLUMN comments to the new Belgium SCS tables

### ISSUE THREAD

**Issue by sfc-gh-space** [starschema/COVID-19-data#175]
**Is your feature request related to a problem? Please describe.**
Similar to your fix to #158, the new SCS tables are missing table and column comments:

![image](https://user-images.githubusercontent.com/53441007/78525082-bcd60400-779b-11ea-9bd3-cdf5722fd7c9.png)

However, the METADATA tables have already been populated for these four tables.

**Describe the solution you'd like**
Please extend your alter column process from #158 to include these 4 new tables. Thanks!

**Additional context**
I would consider amending the METADATA table description to more closely aligned to the description in the project README because it mentions the country (Belgium) in the description.

For instance, for SCS_BE_DETAILED_HOSPITALISATIONS:
Current table desc: Hospitalisations and details on patient disposition
Description from readme: Detailed case counts by province, sex and age band, Belgium

Or if you prefer: Hospitalisations and details on patient disposition, Belgium

**Comment by tfoldi** [comment]
thanks, added!
