### ISSUE TITLE
METADATA table not populated for RKI_GER_COVID19_DASHBOARD

### ISSUE THREAD

**Issue by sfc-gh-space** [starschema/COVID-19-data#193]
**Describe the bug**
The METADATA table holds no values for the RKI_GER_COVID19_DASHBOARD table. Please add.

**To Reproduce**
select * FROM METADATA where "TABLE" = 'RKI_GER_COVID19_DASHBOARD';

**Expected behavior**
Once this is populated, end users can see more detail about what each column does.

**Additional context**
After you populate this table, please run your table alter process from #158 to include this metadata directly in the Snowflake comment fields. Thanks!

**Comment by chrisvoncsefalvay** [comment]
This seems to be related to #192. However, it looks like the data doesn't make it to Snowflake. @tfoldi and I will investigate. 🕵️

**Comment by tfoldi** [comment]
I added the comments manually, but the problem is that the table name is `RKI_GER_COVID19_DASHBOARD` while the METADATA table has `RKI_GER_DETAILED_DASHBOARD` name. I'll search and replace it

**Comment by chrisvoncsefalvay** [comment]
🤦 I'm so sorry. That's my bad. :) Thanks @tfoldi
