### ISSUE TITLE
Please add TABLE and COLUMN comments to the new ViriHealth Canada table

### ISSUE THREAD

**Issue by sfc-gh-space** [starschema/COVID-19-data#194]
**Describe the bug**
Similar to your fix for #158, the new ViriHealth Canada table VH_CAN_DETAILED is missing table and column comments.

![Screen Shot 2020-04-13 at 10 45 36 PM](https://user-images.githubusercontent.com/53441007/79183969-98e87300-7dd8-11ea-844d-750032c3a6f4.png)

![Screen Shot 2020-04-13 at 10 41 48 PM](https://user-images.githubusercontent.com/53441007/79184011-adc50680-7dd8-11ea-988d-e0ab9a28a686.png)

**To Reproduce**
```
show tables;
desc table VH_CAN_DETAILED; 
```

**Expected behavior**
Once this is populated, end users can see more detail about what each column does using native Snowflake functionality, and these fields are also used by some downstream solutions.

**Additional context**
Two of the BC records have a NULL Healthcare Region. Is this something that can be populated from the current source?

```
select * from VH_CAN_DETAILED
where HEALTHCARE_REGION is NULL;
```
![image](https://user-images.githubusercontent.com/53441007/79184205-190ed880-7dd9-11ea-800d-660a0b9e626a.png)

**Comment by chrisvoncsefalvay** [comment]
Closing this down as we're losing Virihealth as a source. :(
