### ISSUE TITLE
Upload data as CSV

### ISSUE THREAD

**Issue by AlexOhayon** [starschema/COVID-19-data#20]
Hi,

Would it be possible to upload the output data as CSV to some location, in addition to the Spreadsheet?

Thanks !

**Comment by tfoldi** [comment]
Absolutely, the CSV is here, refreshed once per a day as JHU: https://s3-us-west-1.amazonaws.com/starschema.covid/JHU_COVID-19.csv

**Comment by AlexOhayon** [comment]
Hi! I've been using the CSV and it's great. It hasn't refreshed since tonight, is there a way to increase the refresh rate of the file?
Thanks !

**Comment by tfoldi** [comment]
It comes from https://github.com/CSSEGISandData/COVID-19 - when that repository refresh we refresh ours
