### ISSUE TITLE
Invalid CSV: HDX_ACAPS.csv

### ISSUE THREAD

**Issue by thlaegler** [starschema/COVID-19-data#204]
**Describe the bug**
The file HDX_ACAPS.csv (https://s3-us-west-1.amazonaws.com/starschema.covid/HDX_ACAPS.csv) is not valid CSV.

**To Reproduce**
1. Parse CSV-file https://s3-us-west-1.amazonaws.com/starschema.covid/HDX_ACAPS.csv
2. Parsing fails with "Error parsing CSV line: 3967. [,Not applicable,2020-04-09 00:00:00.000000,Palau MoH,Government,http://www.palauhealth.org/2019nCoV_SitRep/MOH-COVID-19%20Daily%20Update.pdf,2020-04-15 00:00:00.000000,PW,2020-04-17 00:04:23.338183]"

**Additional context**
Looks like line 3967 misses some columns. Maybe there are more invalid rows following.

**Comment by thlaegler** [comment]
OpenCSV says line **3967** is invalid. However, opening the CSV in Excel shows it's actually line **3861** that is invalid. This difference might be because of line-breaks in the lines above.

**Comment by thlaegler** [comment]
Update: Until yesterday (~24 hours ago) that CSV-file was valid

**Comment by tfoldi** [comment]
I will have a look at it, but we were able to load the same file to our database. Our process uses generic pandas `to_csv` method to save it, so the expectation is that it should work.

I'll let you what did we find

**Comment by thlaegler** [comment]
Thx!
Depending on the parser it might work, but the number of columns is not matching the number of header-columns. At least for the given row

**Comment by tfoldi** [comment]
seems there is a non-printable character at the end of a few fields. Excel considers that as a new line character for some reason. I will force double quotes for that column

![image](https://user-images.githubusercontent.com/82426/79639386-8e700580-8159-11ea-94f8-50fb43386237.png)

**Comment by thlaegler** [comment]
Thanks a lot! 👍
