### ISSUE TITLE
Add new data source: Two new fields in KFF State Data and Policy Actions

### ISSUE THREAD

**Issue by JacinthLaval** [starschema/COVID-19-data#212]
Regarding the StarSchema Covid data, Starschema had an update to their DDL in the publicly available dataset.  2 columns were added that are not in the SF share.  Do you know when SF will have the new fields available?
URL with new fields:
https://www.kff.org/health-costs/issue-brief/state-data-and-policy-actions-to-address-coronavirus/

The new fields are:

‘State Is Easing Social Distancing Measures”

‘'Stay At Home Order”

**Comment by chrisvoncsefalvay** [comment]
@JacinthLaval We'll be pushing code on hopefully early tomorrow EST. I'll let you know when this has been integrated.
