### ISSUE TITLE
KFF_US_STATE_MITIGATIONS. MANDATORY_QUARANTINE not matching source

### ISSUE THREAD

**Issue by psarnow** [starschema/COVID-19-data#225]
Currently the Snowflake DataShare KFF_US_STATE_MITIGATIONS.MANDATORY_QUARANTINE is null for every row. The source [kff](https://www.kff.org/other/state-indicator/state-actions-to-mitigate-the-spread-of-covid-19/) names the column Mandatory Quarantine for Travelers, and is populated with data. I believe the column name should match the source, and map to its data.

**Comment by chrisvoncsefalvay** [comment]
Hi @psarnow, thanks for pointing this out. We're using `MANDATORY_QUARANTINE` for brevity's sake. It refers to mandatory quarantine _for travelers_, of course :)

**Comment by psarnow** [comment]
This column is now populated with the corresponding data from the source table.  Thanks @chrisvoncsefalvay!

**Comment by chrisvoncsefalvay** [comment]
Anytime @psarnow!
