### ISSUE TITLE
Could not download the Raw .csv file from S3 Stage

### ISSUE THREAD

**Issue by saran88** [starschema/COVID-19-data#232]
**Describe the bug**
Could not download Global case counts from s3://starschema.covid/JHU_COVID_19.csv

Below error message is displayed
![image](https://user-images.githubusercontent.com/44474341/80870889-df8a0880-8cc6-11ea-882f-707a1e86d4fe.png)

**Comment by tfoldi** [comment]
Seems to be an issue on our documentation side. Try this:

`https://s3-us-west-1.amazonaws.com/starschema.covid/JHU_COVID-19.csv`

and this:

`s3://starschema.covid/JHU_COVID-19.csv`

Please let me know if any of those are working/not working

**Comment by saran88** [comment]
Thanks this is working.. The issue exists with Global mobility data too. Could you please help with the link for that as well.

**Comment by saran88** [comment]
Hi,

This url: https://s3-us-west-1.amazonaws.com/starschema.covid/JHU_COVID-19.csv works. However, s3://starschema.covid/JHU_COVID-19.csv this dose not.

**Comment by tfoldi** [comment]
Hi Saran, the link for that file is: https://s3-us-west-1.amazonaws.com/starschema.covid/GOOG_GLOBAL_MOBILITY_REPORT.csv - we will fix our links on the front page (cc @chrisvoncsefalvay )

I don't see any reasons why you cannot access the S3 object. Can you try adding `us-west-1` region to the get request?

**Comment by saran88** [comment]
Thanks it works now.. Thanks for helping out on this
