### ISSUE TITLE
Kings County New York in JHU_COVID_19 reporting 0 cases

### ISSUE THREAD

**Issue by psarnow** [starschema/COVID-19-data#241]
**Describe the bug**
There may be more that 'seem' incorrect, but King's is reporting many cases as indicated by JHU's own dashboard.  Here, we have values of 0 cases, and I can't tell why.

**To Reproduce**
```
SELECT * 
FROM jhu_covid_19
WHERE FIPS = '36047';
```
**Expected behavior**
Expecting our target table available here to match what JHU displays.
https://coronavirus.jhu.edu/us-map

**Screenshots**
![image](https://user-images.githubusercontent.com/1322925/81204031-e4c8ab00-8f85-11ea-9075-8124c3e47da5.png)

**Additional context**
I've been searching for 'exceptions' from JHU, but I can find anything pertaining to this.

**Comment by tfoldi** [comment]
We are using the daily data from JHU's repository: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/05-05-2020.csv

This file does not have Kings county in New York

**Comment by psarnow** [comment]
Understood. Problematic that King's county and the other New York City boroughs have rows in the table with case counts of zero though, that is terribly misleading.

**Comment by psarnow** [comment]
Are you aware if any of the tables provided by Starschema here have New York City county level case data?  I'm at a loss so far.

**Comment by tfoldi** [comment]
The most granular is `NYC_HEALTH_TESTS` that has zip code level info too

**Comment by tfoldi** [comment]
It gets data from https://github.com/nychealth/coronavirus-data

**Comment by psarnow** [comment]
awesome. thanks!

**Comment by psarnow** [comment]
> Understood. Problematic that King's county and the other New York City boroughs have rows in the table with case counts of zero though, that is terribly misleading.

May I suggest instead of filling missing FIPS from the daily data in JHU's repository, leaving it out. Not reported is much different than reporting a value of 0.  If the file does not have Kings county in New York, then there should not be a row in the resulting table.

**Comment by tfoldi** [comment]
sounds good, we will remove those old legacy counties with 0 cases

**Comment by psarnow** [comment]
Great! To be clear, don't remove rows from JHU's repo (even if they have zero cases). Just don't create new rows that are not in the JHU repo.
This will help a lot. Thank you.
