### ISSUE TITLE
KFF_US_STATE_MITIGATIONS.BAR_RESTAURANT_LIMITS data went NULL

### ISSUE THREAD

**Issue by psarnow** [starschema/COVID-19-data#242]
**Describe the bug**
KFF_US_STATE_MITIGATIONS.BAR_RESTAURANT_LIMITS data went NULL 

**To Reproduce**
`SELECT BAR_RESTAURANT_LIMITS
FROM KFF_US_STATE_MITIGATIONS;`

**Expected behavior**
Data should match source... https://www.kff.org/other/state-indicator/state-actions-to-mitigate-the-spread-of-covid-19/?currentTimeframe=0&selectedDistributions=restaurant-limits&sortModel=%7B%22colId%22:%22Location%22,%22sort%22:%22asc%22%7D
... and is there a QA tasks to prevent clearing out entire columns?

**Comment by psarnow** [comment]
I believe this might be due to a change of column names in KFF.  Today, they have named this column `Restaurant Limits`, notice the elimination of 'Bar'.
The column will need to be updated in [the notebook](https://render.githubusercontent.com/view/ipynb?commit=a066ed6944932adbd8a50735c97483aa0d36cc43&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f73746172736368656d612f434f5649442d31392d646174612f613036366564363934343933326164626438613530373335633937343833616130643336636334332f6e6f7465626f6f6b732f4b46465f55532e6970796e62&nwo=starschema%2FCOVID-19-data&path=notebooks%2FKFF_US.ipynb&repository_id=245742949&repository_type=Repository#State-Actions-to-Mitigate-the-Spread-of-COVID-19)

**Comment by psarnow** [comment]
Would really appreciate it if this column could be remapped ASAP. Retaining the current column name BAR_RESTAURANT_LIMITS would also help.  Many thanks!

**Comment by psarnow** [comment]
Thank you @piglerp !!

**Comment by tfoldi** [comment]
Should be fixed by now via #244
