### ISSUE TITLE
Add csv to repository

### ISSUE THREAD

**Issue by giocaputo** [starschema/COVID-19-data#28]
Add csv to repository, ofte the google spreedshet does not answer

**Comment by tfoldi** [comment]
Hi @giocaputo , we do have CSVs updated regularly (these ones are real-time):

https://s3-us-west-1.amazonaws.com/starschema.covid/JHU_COVID-19.csv
https://s3-us-west-1.amazonaws.com/starschema.covid/PCM_DPS_COVID19.csv <- this is WIP

More to come.

We have a web data connector to access it easily from Tableau: https://starschema-extensions.s3.amazonaws.com/covid-tableau-online-wdc/index.html 

Does this help? We have google spreadsheet as well, but that's the only one that can be automatically refreshed from Tableau Public.
