### ISSUE TITLE
Table KFF_US_STATE_MITIGATIONS is missing

### ISSUE THREAD

**Issue by joelash** [starschema/COVID-19-data#290]
**Describe the bug**
We are using this dataset via the Snowflake data share and noticed today that the table `KFF_US_STATE_MITIGATIONS` is no longer in our shared database.

**Expected behavior**
The table `KFF_US_STATE_MITIGATIONS` to be present.

**Screenshots**
<img width="285" alt="CleanShot 2020-07-29 at 11 32 27@2x" src="https://user-images.githubusercontent.com/64599/88827169-3781bf80-d18f-11ea-90ad-10f444aaa370.png">

**Additional context**
I see a similar error in #226 that may or may not be related also I saw a [commit](https://github.com/starschema/COVID-19-data/commit/8dae3baec3bf0c79c437dcbbcd88fb72e9e8d557) that possibly addresses the issue; however I am not sure if it is. If it does, when will it be re-ran in the Snowflake datashare?

**Comment by chrisvoncsefalvay** [comment]
Hi @joelash, this was a permissions grant issue, and is now fixed. Thank you!

**Comment by joelash** [comment]
Thanks @chrisvoncsefalvay! Does that mean I'll see the table again after "tomorrow" after the nightly refresh of the shared data through Snowflake?

**Comment by tfoldi** [comment]
This issue impacts us-east snowflake region, and snowflake is working on the fix

**Comment by bscheitlin** [comment]
We are no longer seeing the COUNTRY_REGION column in the KFF_US_STATE_MITIGATIONS table.  Has this been removed or renamed?

**Comment by chrisvoncsefalvay** [comment]
Closing this issue as the table is now fixed and present. Thanks all for letting us know!
