### ISSUE TITLE
Google Mobility Data Not Being Updated: "COVID19"."PUBLIC"."GOOG_GLOBAL_MOBILITY_REPORT"

### ISSUE THREAD

**Issue by shazzak** [starschema/COVID-19-data#293]
**Describe the bug**
"COVID19"."PUBLIC"."GOOG_GLOBAL_MOBILITY_REPORT"

The latest date in the table is 7/28 but the actual data is updated as of 8/14/20

https://www.google.com/covid19/mobility/

**Comment by tfoldi** [comment]
fixed via #296 and #294
