### ISSUE TITLE
IHME_COVID_19 - Datasource not found anymore

### ISSUE THREAD

**Issue by ghost** [starschema/COVID-19-data#338]
**Describe the bug**
IHME_COVID_19 load fails to run - remote datasource cannot be reached

**To Reproduce**
Datasource seems to be down - https://ihmecovid19storage.blob.core.windows.net/latest/ihme-covid19.zip -> DNS_PROBE_FINISHED_NXDOMAIN

**Comment by tfoldi** [comment]
seems an issue on their end: http://www.healthdata.org/covid/data-downloads
