### ISSUE TITLE
Data quality issue: JHU_COVID_19/JHU_COVID_19_TIMESERIES/JHU_DASHBOARD_COVID_19_GLOBAL

### ISSUE THREAD

**Issue by sfc-gh-vnair** [starschema/COVID-19-data#363]
**Issue**

The below three tables have no data post 9th/10th March 2023:
SELECT MAX(DATE) FROM JHU_COVID_19;
_-- 2023-03-09_

SELECT MAX(DATE) FROM JHU_COVID_19_TIMESERIES;
_-- 2023-03-09_

SELECT MAX(DATE) FROM JHU_DASHBOARD_COVID_19_GLOBAL;
**-- 2023-03-10**

Ask
Can we expect data beyond 9th/10 March 2023 in these tables? If not, what is the reason?

**Comment by tfoldi** [comment]
No, unfortunately, John Hopkins University stopped updating their numbers: https://github.com/govex/COVID-19

You can still use CDC or WHO data sources.


fixed by #364
