### ISSUE TITLE
Move `Case_Type` to columns

### ISSUE THREAD

**Issue by tfoldi** [starschema/COVID-19-data#5]
We should have columns like `Confirmed` , `Confirmed_Since_Previous_day`, `Recovered` and `Recovered_Since_Previous_day` for each entry. It will allow aggregating the data without using the `Case_Type` as filter or slicer, reducing the confusion.

**Comment by tfoldi** [comment]
@chrisvoncsefalvay do you agree?

**Comment by tfoldi** [comment]
we should move this to a separate table

**Comment by nkamkolkar** [comment]
@tfoldi this will be a breaking change for existing tableau vizes. I realize a lot of other folks are also using the data. Would be great to notify the tableau users of this change. I am trying to gather these changes here: https://community.tableau.com/thread/334105. Could we update the thread with any breaking changes? or tag me and I can help.

**Comment by tfoldi** [comment]
I plan to do it in separate table / flow, without impacting we have today.

**Comment by chrisvoncsefalvay** [comment]
Because this would break too many things at once, we are not currently doing this. Thanks for everyone's comments and contributions.
