### ISSUE TITLE
Automate acqusition of KFF dataset

### ISSUE THREAD

**Issue by tfoldi** [starschema/COVID-19-data#52]
https://www.kff.org/health-costs/issue-brief/state-data-and-policy-actions-to-address-coronavirus/

The daily updated tables should be available thru notebooks and airflow

**Comment by chrisvoncsefalvay** [comment]
I can possibly give this a try. We'd be using `bs4` to get the table and parse its contents. As long as the table schema does not change significantly, this should be fine.
