### ISSUE TITLE
Data for 23th March 2020 seems wrong.

### ISSUE THREAD

**Issue by azmilmacksood** [starschema/COVID-19-data#67]
E.g.

United States

20-Mar | 10846
21-Mar | 12778
22-Mar | 15566
23-Mar | 8

**Comment by tfoldi** [comment]
Yesterday JHU changed their data feeds: https://github.com/CSSEGISandData/COVID-19/issues/1250 

They still do not have the updated US numbers. We are working on the new file format and update it soon.

**Comment by tfoldi** [comment]
Fixed for today:

![image](https://user-images.githubusercontent.com/82426/77434248-f3cd1280-6db6-11ea-92d7-2da010b814f0.png)

JHU changes are still in progress, tomorrow they will introduce new US files. We will keep changing our loads to support the new format
