### ISSUE TITLE
Double entries for some countries

### ISSUE THREAD

**Issue by JoaoRodrigues** [starschema/COVID-19-data#69]
Hi there,

First off, thanks a ton for collating and curating these datasets. There are way too many sources of data and far too few people making sure they make sense, so work like yours is very important for everyone interested in analysis or just more detailed information.

I found what I believe is an issue with duplicated entries in the dataset. East Timor and Cape Verde show up twice, once with their translated names and once with their (native?) names (Timor-Leste and Cabo Verde). Both East Timor and Cape Verde appear only on the 'Recovered' sub-dataset. 

Not sure where/why this might be wrong and not sure if these are the only cases, but wanted to let you know so you can have a look!

Thanks again!

**Comment by chrisvoncsefalvay** [comment]
Thanks @JoaoRodrigues, we've fixed this in #73 by standardising to the ISO3166-1 names:

* East Timor to Timor-Leste, and 
* Cape Verde to Cabo Verde.
