### ISSUE TITLE
Update Metadata table to include entity level descriptions

### ISSUE THREAD

**Issue by william-wash** [starschema/COVID-19-data#98]
Maybe add a row with no column name so you can add a description on the table level.

**Comment by chrisvoncsefalvay** [comment]
Good idea. I'll get right on to it!

**Comment by tfoldi** [comment]
please keep a column for recent notes, like DQ issues and recent changes

**Comment by chrisvoncsefalvay** [comment]
@tfoldi 👍 that would go into the table-level row's comment column.
